spring:
  application:
    name: homepage-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: MY_USER
    password: MY_PASS
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mail-sender:
  host: ${spring.mail.host}
  port: ${spring.mail.port}
  username: ${spring.mail.username}
  password: ${spring.mail.password}
  auth: true
  starttls-enable: true