spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sb-app
    username: sb-app
    password: sb-app
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    ROOT: DEBUG
    nl.rcomanne: DEBUG